'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'StronglyTypedResourceBuilder generó automáticamente esta clase
'a través de una herramienta como ResGen o Visual Studio.
'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
'con la opción /str o recompile su proyecto de VS.
'''<summary>
'''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Public Class Language
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FileRenamer.Language", GetType(Language).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a There is a new version available.
    '''</summary>
    Public Shared ReadOnly Property acerca_de_actualizaciones() As String
        Get
            Return ResourceManager.GetString("acerca_de_actualizaciones", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Could not load the version changes.
    '''</summary>
    Public Shared ReadOnly Property acerca_de_cambios_error() As String
        Get
            Return ResourceManager.GetString("acerca_de_cambios_error", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a For any doubt, suggestion or error you want to report send a mail to andres.cirulo@gmail.com.
    '''</summary>
    Public Shared ReadOnly Property acerca_de_contacto() As String
        Get
            Return ResourceManager.GetString("acerca_de_contacto", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Downloading....
    '''</summary>
    Public Shared ReadOnly Property acerca_de_descargando() As String
        Get
            Return ResourceManager.GetString("acerca_de_descargando", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Version Details.
    '''</summary>
    Public Shared ReadOnly Property acerca_de_detalles() As String
        Get
            Return ResourceManager.GetString("acerca_de_detalles", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Install.
    '''</summary>
    Public Shared ReadOnly Property acerca_de_instalar() As String
        Get
            Return ResourceManager.GetString("acerca_de_instalar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a You have the most recent version.
    '''</summary>
    Public Shared ReadOnly Property acerca_de_no_actualizaciones() As String
        Get
            Return ResourceManager.GetString("acerca_de_no_actualizaciones", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Back.
    '''</summary>
    Public Shared ReadOnly Property btn_atras() As String
        Get
            Return ResourceManager.GetString("btn_atras", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Right Click while pressing Shift key.
    '''</summary>
    Public Shared ReadOnly Property config_cuando_extendido() As String
        Get
            Return ResourceManager.GetString("config_cuando_extendido", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Right Click.
    '''</summary>
    Public Shared ReadOnly Property config_cuando_normal() As String
        Get
            Return ResourceManager.GetString("config_cuando_normal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Show When.
    '''</summary>
    Public Shared ReadOnly Property config_cuando_titulo() As String
        Get
            Return ResourceManager.GetString("config_cuando_titulo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Folder Name Right Click.
    '''</summary>
    Public Shared ReadOnly Property config_donde_carpeta() As String
        Get
            Return ResourceManager.GetString("config_donde_carpeta", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Folder Background Right Click.
    '''</summary>
    Public Shared ReadOnly Property config_donde_fondo() As String
        Get
            Return ResourceManager.GetString("config_donde_fondo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Show At.
    '''</summary>
    Public Shared ReadOnly Property config_donde_titulo() As String
        Get
            Return ResourceManager.GetString("config_donde_titulo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Save.
    '''</summary>
    Public Shared ReadOnly Property config_guardar() As String
        Get
            Return ResourceManager.GetString("config_guardar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Subtitles Context Menu.
    '''</summary>
    Public Shared ReadOnly Property config_menu_contextual() As String
        Get
            Return ResourceManager.GetString("config_menu_contextual", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Enable Windows Explorer Context Menu.
    '''</summary>
    Public Shared ReadOnly Property config_menu_contextual_habilitar() As String
        Get
            Return ResourceManager.GetString("config_menu_contextual_habilitar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Rename Subtitles.
    '''</summary>
    Public Shared ReadOnly Property contextual_procesar() As String
        Get
            Return ResourceManager.GetString("contextual_procesar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Application information and updates.
    '''</summary>
    Public Shared ReadOnly Property inicio_acerca_de() As String
        Get
            Return ResourceManager.GetString("inicio_acerca_de", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Adjust the application configuration.
    '''</summary>
    Public Shared ReadOnly Property inicio_configuracion() As String
        Get
            Return ResourceManager.GetString("inicio_configuracion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Rename Mp3 files based on their ID3 tags.
    '''</summary>
    Public Shared ReadOnly Property inicio_mp3() As String
        Get
            Return ResourceManager.GetString("inicio_mp3", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Rename files using a set of operations of your choice.
    '''</summary>
    Public Shared ReadOnly Property inicio_renombrar() As String
        Get
            Return ResourceManager.GetString("inicio_renombrar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Rename Subtitles files so they have the same name that their correspondig Video file.
    '''</summary>
    Public Shared ReadOnly Property inicio_subtitulos() As String
        Get
            Return ResourceManager.GetString("inicio_subtitulos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Files Renamed!!.
    '''</summary>
    Public Shared ReadOnly Property mp3_correcto() As String
        Get
            Return ResourceManager.GetString("mp3_correcto", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a You have to select at least one file.
    '''</summary>
    Public Shared ReadOnly Property mp3_falta_archivo() As String
        Get
            Return ResourceManager.GetString("mp3_falta_archivo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a You have to add something to the formula.
    '''</summary>
    Public Shared ReadOnly Property mp3_falta_formula() As String
        Get
            Return ResourceManager.GetString("mp3_falta_formula", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a The result contains repeated names, fix it.
    '''</summary>
    Public Shared ReadOnly Property mp3_repetidos() As String
        Get
            Return ResourceManager.GetString("mp3_repetidos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Add.
    '''</summary>
    Public Shared ReadOnly Property renombrar_agregar() As String
        Get
            Return ResourceManager.GetString("renombrar_agregar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Down.
    '''</summary>
    Public Shared ReadOnly Property renombrar_bajar() As String
        Get
            Return ResourceManager.GetString("renombrar_bajar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Files Renamed!!.
    '''</summary>
    Public Shared ReadOnly Property renombrar_correcto() As String
        Get
            Return ResourceManager.GetString("renombrar_correcto", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a You must choose at least one file.
    '''</summary>
    Public Shared ReadOnly Property renombrar_error_archivos() As String
        Get
            Return ResourceManager.GetString("renombrar_error_archivos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a You must choose at least one operation.
    '''</summary>
    Public Shared ReadOnly Property renombrar_error_operaciones() As String
        Get
            Return ResourceManager.GetString("renombrar_error_operaciones", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Include Subfolders.
    '''</summary>
    Public Shared ReadOnly Property renombrar_incluir_subcarpetas() As String
        Get
            Return ResourceManager.GetString("renombrar_incluir_subcarpetas", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Operation.
    '''</summary>
    Public Shared ReadOnly Property renombrar_operacion() As String
        Get
            Return ResourceManager.GetString("renombrar_operacion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Operations Available.
    '''</summary>
    Public Shared ReadOnly Property renombrar_operaciones() As String
        Get
            Return ResourceManager.GetString("renombrar_operaciones", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Operations Selected.
    '''</summary>
    Public Shared ReadOnly Property renombrar_operaciones_elegidas() As String
        Get
            Return ResourceManager.GetString("renombrar_operaciones_elegidas", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a for.
    '''</summary>
    Public Shared ReadOnly Property renombrar_por() As String
        Get
            Return ResourceManager.GetString("renombrar_por", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Remove.
    '''</summary>
    Public Shared ReadOnly Property renombrar_quitar() As String
        Get
            Return ResourceManager.GetString("renombrar_quitar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Replace.
    '''</summary>
    Public Shared ReadOnly Property renombrar_reemplazar() As String
        Get
            Return ResourceManager.GetString("renombrar_reemplazar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No Folder Selected.
    '''</summary>
    Public Shared ReadOnly Property renombrar_sin_seleccionar() As String
        Get
            Return ResourceManager.GetString("renombrar_sin_seleccionar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Up.
    '''</summary>
    Public Shared ReadOnly Property renombrar_subir() As String
        Get
            Return ResourceManager.GetString("renombrar_subir", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Preview.
    '''</summary>
    Public Shared ReadOnly Property renombrar_vista_previa() As String
        Get
            Return ResourceManager.GetString("renombrar_vista_previa", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Rename.
    '''</summary>
    Public Shared ReadOnly Property resultado_renombrar() As String
        Get
            Return ResourceManager.GetString("resultado_renombrar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a AC FileRenamer - Preview.
    '''</summary>
    Public Shared ReadOnly Property resultado_titulo() As String
        Get
            Return ResourceManager.GetString("resultado_titulo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Result preview.
    '''</summary>
    Public Shared ReadOnly Property resultado_vista_previa() As String
        Get
            Return ResourceManager.GetString("resultado_vista_previa", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Unselect All.
    '''</summary>
    Public Shared ReadOnly Property subtitulos_desmarcar_todos() As String
        Get
            Return ResourceManager.GetString("subtitulos_desmarcar_todos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a You must choose at least one file.
    '''</summary>
    Public Shared ReadOnly Property subtitulos_error_archivos() As String
        Get
            Return ResourceManager.GetString("subtitulos_error_archivos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Select All.
    '''</summary>
    Public Shared ReadOnly Property subtitulos_marcar_todos() As String
        Get
            Return ResourceManager.GetString("subtitulos_marcar_todos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Rename Selected.
    '''</summary>
    Public Shared ReadOnly Property subtitulos_renombrar() As String
        Get
            Return ResourceManager.GetString("subtitulos_renombrar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No Folder Selected.
    '''</summary>
    Public Shared ReadOnly Property subtitulos_sin_seleccionar() As String
        Get
            Return ResourceManager.GetString("subtitulos_sin_seleccionar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a About.
    '''</summary>
    Public Shared ReadOnly Property tab_acerca_de() As String
        Get
            Return ResourceManager.GetString("tab_acerca_de", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Configuration.
    '''</summary>
    Public Shared ReadOnly Property tab_configuracion() As String
        Get
            Return ResourceManager.GetString("tab_configuracion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Rename Files.
    '''</summary>
    Public Shared ReadOnly Property tab_renombrar_archivos() As String
        Get
            Return ResourceManager.GetString("tab_renombrar_archivos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Rename Mp3.
    '''</summary>
    Public Shared ReadOnly Property tab_renombrar_mp3() As String
        Get
            Return ResourceManager.GetString("tab_renombrar_mp3", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Rename Subtitles.
    '''</summary>
    Public Shared ReadOnly Property tab_renombrar_subtitulos() As String
        Get
            Return ResourceManager.GetString("tab_renombrar_subtitulos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a There is a new version available, click here.
    '''</summary>
    Public Shared ReadOnly Property toolbar_actualizacion() As String
        Get
            Return ResourceManager.GetString("toolbar_actualizacion", resourceCulture)
        End Get
    End Property
End Class
