'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'StronglyTypedResourceBuilder generó automáticamente esta clase
'a través de una herramienta como ResGen o Visual Studio.
'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
'con la opción /str o recompile su proyecto de VS.
'''<summary>
'''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Public Class LangMp3
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FileRenamer.LangMp3", GetType(LangMp3).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Example:.
    '''</summary>
    Public Shared ReadOnly Property ejemplo() As String
        Get
            Return ResourceManager.GetString("ejemplo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Available Tags.
    '''</summary>
    Public Shared ReadOnly Property etiquetas_disponibles() As String
        Get
            Return ResourceManager.GetString("etiquetas_disponibles", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Drag and drop a tag or click on the + to add it to the formula..
    '''</summary>
    Public Shared ReadOnly Property etiquetas_explicacion() As String
        Get
            Return ResourceManager.GetString("etiquetas_explicacion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Formula: .
    '''</summary>
    Public Shared ReadOnly Property formula() As String
        Get
            Return ResourceManager.GetString("formula", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Build a Formula to rename the files using the Available Tags or editing it yourself. Below you will see an example of the result..
    '''</summary>
    Public Shared ReadOnly Property formula_explicacion() As String
        Get
            Return ResourceManager.GetString("formula_explicacion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Album.
    '''</summary>
    Public Shared ReadOnly Property header_album() As String
        Get
            Return ResourceManager.GetString("header_album", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Year.
    '''</summary>
    Public Shared ReadOnly Property header_anio() As String
        Get
            Return ResourceManager.GetString("header_anio", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Filename.
    '''</summary>
    Public Shared ReadOnly Property header_archivo() As String
        Get
            Return ResourceManager.GetString("header_archivo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Artist.
    '''</summary>
    Public Shared ReadOnly Property header_artista() As String
        Get
            Return ResourceManager.GetString("header_artista", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Disc.
    '''</summary>
    Public Shared ReadOnly Property header_disco() As String
        Get
            Return ResourceManager.GetString("header_disco", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Genre.
    '''</summary>
    Public Shared ReadOnly Property header_genero() As String
        Get
            Return ResourceManager.GetString("header_genero", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Track.
    '''</summary>
    Public Shared ReadOnly Property header_pista() As String
        Get
            Return ResourceManager.GetString("header_pista", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Title.
    '''</summary>
    Public Shared ReadOnly Property header_titulo() As String
        Get
            Return ResourceManager.GetString("header_titulo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Total Discs.
    '''</summary>
    Public Shared ReadOnly Property header_total_discos() As String
        Get
            Return ResourceManager.GetString("header_total_discos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Total Tracks.
    '''</summary>
    Public Shared ReadOnly Property header_total_pistas() As String
        Get
            Return ResourceManager.GetString("header_total_pistas", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Album.
    '''</summary>
    Public Shared ReadOnly Property tag_album_nombre() As String
        Get
            Return ResourceManager.GetString("tag_album_nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a &lt;Album&gt;.
    '''</summary>
    Public Shared ReadOnly Property tag_album_valor() As String
        Get
            Return ResourceManager.GetString("tag_album_valor", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Year.
    '''</summary>
    Public Shared ReadOnly Property tag_anio_nombre() As String
        Get
            Return ResourceManager.GetString("tag_anio_nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a &lt;Year&gt;.
    '''</summary>
    Public Shared ReadOnly Property tag_anio_valor() As String
        Get
            Return ResourceManager.GetString("tag_anio_valor", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Artist.
    '''</summary>
    Public Shared ReadOnly Property tag_artista_nombre() As String
        Get
            Return ResourceManager.GetString("tag_artista_nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a &lt;Artist&gt;.
    '''</summary>
    Public Shared ReadOnly Property tag_artista_valor() As String
        Get
            Return ResourceManager.GetString("tag_artista_valor", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Disc.
    '''</summary>
    Public Shared ReadOnly Property tag_disco_nombre() As String
        Get
            Return ResourceManager.GetString("tag_disco_nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a &lt;Disc&gt;.
    '''</summary>
    Public Shared ReadOnly Property tag_disco_valor() As String
        Get
            Return ResourceManager.GetString("tag_disco_valor", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Genre.
    '''</summary>
    Public Shared ReadOnly Property tag_genero_nombre() As String
        Get
            Return ResourceManager.GetString("tag_genero_nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a &lt;Genre&gt;.
    '''</summary>
    Public Shared ReadOnly Property tag_genero_valor() As String
        Get
            Return ResourceManager.GetString("tag_genero_valor", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Track.
    '''</summary>
    Public Shared ReadOnly Property tag_pista_nombre() As String
        Get
            Return ResourceManager.GetString("tag_pista_nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a &lt;Track&gt;.
    '''</summary>
    Public Shared ReadOnly Property tag_pista_valor() As String
        Get
            Return ResourceManager.GetString("tag_pista_valor", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Title.
    '''</summary>
    Public Shared ReadOnly Property tag_titulo_nombre() As String
        Get
            Return ResourceManager.GetString("tag_titulo_nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a &lt;Title&gt;.
    '''</summary>
    Public Shared ReadOnly Property tag_titulo_valor() As String
        Get
            Return ResourceManager.GetString("tag_titulo_valor", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a TotalDiscs.
    '''</summary>
    Public Shared ReadOnly Property tag_total_discos_nombre() As String
        Get
            Return ResourceManager.GetString("tag_total_discos_nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a &lt;TotalDiscs&gt;.
    '''</summary>
    Public Shared ReadOnly Property tag_total_discos_valor() As String
        Get
            Return ResourceManager.GetString("tag_total_discos_valor", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a TotalTracks.
    '''</summary>
    Public Shared ReadOnly Property tag_total_pistas_nombre() As String
        Get
            Return ResourceManager.GetString("tag_total_pistas_nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a &lt;TotalTracks&gt;.
    '''</summary>
    Public Shared ReadOnly Property tag_total_pistas_valor() As String
        Get
            Return ResourceManager.GetString("tag_total_pistas_valor", resourceCulture)
        End Get
    End Property
End Class
