'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'StronglyTypedResourceBuilder generó automáticamente esta clase
'a través de una herramienta como ResGen o Visual Studio.
'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
'con la opción /str o recompile su proyecto de VS.
'''<summary>
'''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Public Class Operaciones
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FileRenamer.Operaciones", GetType(Operaciones).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Adds the specified text at the end of the filename, before the extension.
    '''</summary>
    Public Shared ReadOnly Property AgregarAlFinalDelNombre_Descripcion() As String
        Get
            Return ResourceManager.GetString("AgregarAlFinalDelNombre_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Add at the end of the filename.
    '''</summary>
    Public Shared ReadOnly Property AgregarAlFinalDelNombre_Nombre() As String
        Get
            Return ResourceManager.GetString("AgregarAlFinalDelNombre_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Add &quot;{1}&quot; at the end of the filename.
    '''</summary>
    Public Shared ReadOnly Property AgregarAlFinalDelNombre_ToString() As String
        Get
            Return ResourceManager.GetString("AgregarAlFinalDelNombre_ToString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Adds the specified text at the end of the filename, after the extension.
    '''</summary>
    Public Shared ReadOnly Property AgregarAlFinalDeTodo_Descripcion() As String
        Get
            Return ResourceManager.GetString("AgregarAlFinalDeTodo_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Add at the end of the filename (after the extension).
    '''</summary>
    Public Shared ReadOnly Property AgregarAlFinalDeTodo_Nombre() As String
        Get
            Return ResourceManager.GetString("AgregarAlFinalDeTodo_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Add &quot;{1}&quot; after the extension of the filename.
    '''</summary>
    Public Shared ReadOnly Property AgregarAlFinalDeTodo_ToString() As String
        Get
            Return ResourceManager.GetString("AgregarAlFinalDeTodo_ToString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Adds the specified text at the begining of the filename.
    '''</summary>
    Public Shared ReadOnly Property AgregarAlPrincipio_Descripcion() As String
        Get
            Return ResourceManager.GetString("AgregarAlPrincipio_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Add at the begining of the filename.
    '''</summary>
    Public Shared ReadOnly Property AgregarAlPrincipio_Nombre() As String
        Get
            Return ResourceManager.GetString("AgregarAlPrincipio_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Add &quot;{1}&quot; at the begining of the filename.
    '''</summary>
    Public Shared ReadOnly Property AgregarAlPrincipio_ToString() As String
        Get
            Return ResourceManager.GetString("AgregarAlPrincipio_ToString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Repetitions.:.
    '''</summary>
    Public Shared ReadOnly Property AgregarPadding_Cantidad() As String
        Get
            Return ResourceManager.GetString("AgregarPadding_Cantidad", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Character:.
    '''</summary>
    Public Shared ReadOnly Property AgregarPadding_Caracter() As String
        Get
            Return ResourceManager.GetString("AgregarPadding_Caracter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Adds the specified character at the begining of the filename until it&apos;s length is the specified.
    '''</summary>
    Public Shared ReadOnly Property AgregarPadding_Descripcion() As String
        Get
            Return ResourceManager.GetString("AgregarPadding_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Add padding.
    '''</summary>
    Public Shared ReadOnly Property AgregarPadding_Nombre() As String
        Get
            Return ResourceManager.GetString("AgregarPadding_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Add &quot;{1}&quot; until reaching {2} characters.
    '''</summary>
    Public Shared ReadOnly Property AgregarPadding_ToString() As String
        Get
            Return ResourceManager.GetString("AgregarPadding_ToString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Removes the text between the specified characters, including the boundary characters.
    '''</summary>
    Public Shared ReadOnly Property EliminarEntreCaracteres_Descripcion() As String
        Get
            Return ResourceManager.GetString("EliminarEntreCaracteres_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Remove between characters (without including the extension).
    '''</summary>
    Public Shared ReadOnly Property EliminarEntreCaracteres_Nombre() As String
        Get
            Return ResourceManager.GetString("EliminarEntreCaracteres_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Remove text between &quot;{1}&quot; and &quot;{2}&quot;.
    '''</summary>
    Public Shared ReadOnly Property EliminarEntreCaracteres_ToString() As String
        Get
            Return ResourceManager.GetString("EliminarEntreCaracteres_ToString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Converts the text to lowercase and uppercase separating by word.
    '''</summary>
    Public Shared ReadOnly Property MayusculasYMinusculas_Descripcion() As String
        Get
            Return ResourceManager.GetString("MayusculasYMinusculas_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Uppercase and LowerCase.
    '''</summary>
    Public Shared ReadOnly Property MayusculasYMinusculas_Nombre() As String
        Get
            Return ResourceManager.GetString("MayusculasYMinusculas_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Convert Uppercase and Lowercase.
    '''</summary>
    Public Shared ReadOnly Property MayusculasYMinusculas_ToString() As String
        Get
            Return ResourceManager.GetString("MayusculasYMinusculas_ToString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Between.
    '''</summary>
    Public Shared ReadOnly Property Operacion_Entre() As String
        Get
            Return ResourceManager.GetString("Operacion_Entre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a and.
    '''</summary>
    Public Shared ReadOnly Property Operacion_Y() As String
        Get
            Return ResourceManager.GetString("Operacion_Y", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Replace one text for another in the filename, including the extension.
    '''</summary>
    Public Shared ReadOnly Property Reemplazo_Descripcion() As String
        Get
            Return ResourceManager.GetString("Reemplazo_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Replace (including the extension).
    '''</summary>
    Public Shared ReadOnly Property Reemplazo_Nombre() As String
        Get
            Return ResourceManager.GetString("Reemplazo_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Replace &quot;{1}&quot; for &quot;{2}&quot; (including the extension).
    '''</summary>
    Public Shared ReadOnly Property Reemplazo_ToString() As String
        Get
            Return ResourceManager.GetString("Reemplazo_ToString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Replace one text for another in the filename, without including the extension.
    '''</summary>
    Public Shared ReadOnly Property ReemplazoEnNombre_Descripcion() As String
        Get
            Return ResourceManager.GetString("ReemplazoEnNombre_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Replace (without including the extension).
    '''</summary>
    Public Shared ReadOnly Property ReemplazoEnNombre_Nombre() As String
        Get
            Return ResourceManager.GetString("ReemplazoEnNombre_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Replace &quot;{1}&quot; for &quot;{2}&quot; (without including the extension).
    '''</summary>
    Public Shared ReadOnly Property ReemplazoEnNombre_ToString() As String
        Get
            Return ResourceManager.GetString("ReemplazoEnNombre_ToString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Keeps only the text between the specified characters without including the boundary characters.
    '''</summary>
    Public Shared ReadOnly Property SoloEntreCaracteres_Descripcion() As String
        Get
            Return ResourceManager.GetString("SoloEntreCaracteres_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Only between characters (without including the extension).
    '''</summary>
    Public Shared ReadOnly Property SoloEntreCaracteres_Nombre() As String
        Get
            Return ResourceManager.GetString("SoloEntreCaracteres_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Only text between &quot;{1}&quot; and &quot;{2}&quot;.
    '''</summary>
    Public Shared ReadOnly Property SoloEntreCaracteres_ToString() As String
        Get
            Return ResourceManager.GetString("SoloEntreCaracteres_ToString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Converts all the filename to Uppercase.
    '''</summary>
    Public Shared ReadOnly Property TodoAMayusculas_Descripcion() As String
        Get
            Return ResourceManager.GetString("TodoAMayusculas_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Convert filename to Uppercase.
    '''</summary>
    Public Shared ReadOnly Property TodoAMayusculas_Nombre() As String
        Get
            Return ResourceManager.GetString("TodoAMayusculas_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Convert filename to Uppercase.
    '''</summary>
    Public Shared ReadOnly Property TodoAMayusculas_ToString() As String
        Get
            Return ResourceManager.GetString("TodoAMayusculas_ToString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Converts all the filename to Lowercase.
    '''</summary>
    Public Shared ReadOnly Property TodoAMinusculas_Descripcion() As String
        Get
            Return ResourceManager.GetString("TodoAMinusculas_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Convert filename to Lowercase.
    '''</summary>
    Public Shared ReadOnly Property TodoAMinusculas_Nombre() As String
        Get
            Return ResourceManager.GetString("TodoAMinusculas_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Convert filename to Lowercase.
    '''</summary>
    Public Shared ReadOnly Property TodoAMinusculas_ToString() As String
        Get
            Return ResourceManager.GetString("TodoAMinusculas_ToString", resourceCulture)
        End Get
    End Property
End Class
