'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'StronglyTypedResourceBuilder generó automáticamente esta clase
'a través de una herramienta como ResGen o Visual Studio.
'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
'con la opción /str o recompile su proyecto de VS.
'''<summary>
'''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Public Class Operaciones
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FileRenamer.Operaciones", GetType(Operaciones).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Agrega el texto especificado al final del nombre del archivo, antes de su extensión.
    '''</summary>
    Public Shared ReadOnly Property AgregarAlFinalDelNombre_Descripcion() As String
        Get
            Return ResourceManager.GetString("AgregarAlFinalDelNombre_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Agregar al final del nombre.
    '''</summary>
    Public Shared ReadOnly Property AgregarAlFinalDelNombre_Nombre() As String
        Get
            Return ResourceManager.GetString("AgregarAlFinalDelNombre_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Agregar &quot;{1}&quot; al final del nombre.
    '''</summary>
    Public Shared ReadOnly Property AgregarAlFinalDelNombre_ToString() As String
        Get
            Return ResourceManager.GetString("AgregarAlFinalDelNombre_ToString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Agrega el texto especificado al final del nombre del archivo, luego de su extensión.
    '''</summary>
    Public Shared ReadOnly Property AgregarAlFinalDeTodo_Descripcion() As String
        Get
            Return ResourceManager.GetString("AgregarAlFinalDeTodo_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Agregar al final de todo.
    '''</summary>
    Public Shared ReadOnly Property AgregarAlFinalDeTodo_Nombre() As String
        Get
            Return ResourceManager.GetString("AgregarAlFinalDeTodo_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Agregar &quot;{1}&quot; al final de todo.
    '''</summary>
    Public Shared ReadOnly Property AgregarAlFinalDeTodo_ToString() As String
        Get
            Return ResourceManager.GetString("AgregarAlFinalDeTodo_ToString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Agrega el texto especificado al inicio del nombre del archivo.
    '''</summary>
    Public Shared ReadOnly Property AgregarAlPrincipio_Descripcion() As String
        Get
            Return ResourceManager.GetString("AgregarAlPrincipio_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Agregar al principio del nombre.
    '''</summary>
    Public Shared ReadOnly Property AgregarAlPrincipio_Nombre() As String
        Get
            Return ResourceManager.GetString("AgregarAlPrincipio_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Agregar &quot;{1}&quot; al principio del nombre.
    '''</summary>
    Public Shared ReadOnly Property AgregarAlPrincipio_ToString() As String
        Get
            Return ResourceManager.GetString("AgregarAlPrincipio_ToString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Cant.:.
    '''</summary>
    Public Shared ReadOnly Property AgregarPadding_Cantidad() As String
        Get
            Return ResourceManager.GetString("AgregarPadding_Cantidad", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Caracter:.
    '''</summary>
    Public Shared ReadOnly Property AgregarPadding_Caracter() As String
        Get
            Return ResourceManager.GetString("AgregarPadding_Caracter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Agrega el caracter especificado la cantidad de veces especificada al inicio del nombre del archivo.
    '''</summary>
    Public Shared ReadOnly Property AgregarPadding_Descripcion() As String
        Get
            Return ResourceManager.GetString("AgregarPadding_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Agregar padding.
    '''</summary>
    Public Shared ReadOnly Property AgregarPadding_Nombre() As String
        Get
            Return ResourceManager.GetString("AgregarPadding_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Agregar &quot;{1}&quot; hasta llegar a {2} caracteres.
    '''</summary>
    Public Shared ReadOnly Property AgregarPadding_ToString() As String
        Get
            Return ResourceManager.GetString("AgregarPadding_ToString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Elimina todo el texto entre los caracteres especificados, inclusive los caracteres límite.
    '''</summary>
    Public Shared ReadOnly Property EliminarEntreCaracteres_Descripcion() As String
        Get
            Return ResourceManager.GetString("EliminarEntreCaracteres_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Eliminar entre caracteres (sin incluir la extension).
    '''</summary>
    Public Shared ReadOnly Property EliminarEntreCaracteres_Nombre() As String
        Get
            Return ResourceManager.GetString("EliminarEntreCaracteres_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Eliminar texto entre &quot;{1}&quot; y &quot;{2}&quot;.
    '''</summary>
    Public Shared ReadOnly Property EliminarEntreCaracteres_ToString() As String
        Get
            Return ResourceManager.GetString("EliminarEntreCaracteres_ToString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Convierte el texto a mayúsculas y minúsculas separando por palabra.
    '''</summary>
    Public Shared ReadOnly Property MayusculasYMinusculas_Descripcion() As String
        Get
            Return ResourceManager.GetString("MayusculasYMinusculas_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Mayúsculas y Minúsculas.
    '''</summary>
    Public Shared ReadOnly Property MayusculasYMinusculas_Nombre() As String
        Get
            Return ResourceManager.GetString("MayusculasYMinusculas_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Colocar Mayúsculas y Minúsculas.
    '''</summary>
    Public Shared ReadOnly Property MayusculasYMinusculas_ToString() As String
        Get
            Return ResourceManager.GetString("MayusculasYMinusculas_ToString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Entre.
    '''</summary>
    Public Shared ReadOnly Property Operacion_Entre() As String
        Get
            Return ResourceManager.GetString("Operacion_Entre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a y.
    '''</summary>
    Public Shared ReadOnly Property Operacion_Y() As String
        Get
            Return ResourceManager.GetString("Operacion_Y", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Reemplaza un texto por otro en el nombre del archivo, incluyendo la extension.
    '''</summary>
    Public Shared ReadOnly Property Reemplazo_Descripcion() As String
        Get
            Return ResourceManager.GetString("Reemplazo_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Reemplazar (inclusive en la extension).
    '''</summary>
    Public Shared ReadOnly Property Reemplazo_Nombre() As String
        Get
            Return ResourceManager.GetString("Reemplazo_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Reemplazar &quot;{1}&quot; por &quot;{2}&quot;.
    '''</summary>
    Public Shared ReadOnly Property Reemplazo_ToString() As String
        Get
            Return ResourceManager.GetString("Reemplazo_ToString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Reemplaza un texto por otro en el nombre del archivo, sin incluír la extension.
    '''</summary>
    Public Shared ReadOnly Property ReemplazoEnNombre_Descripcion() As String
        Get
            Return ResourceManager.GetString("ReemplazoEnNombre_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Reemplazar (sin incluir la extension).
    '''</summary>
    Public Shared ReadOnly Property ReemplazoEnNombre_Nombre() As String
        Get
            Return ResourceManager.GetString("ReemplazoEnNombre_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Reemplazar &quot;{1}&quot; por &quot;{2}&quot;.
    '''</summary>
    Public Shared ReadOnly Property ReemplazoEnNombre_ToString() As String
        Get
            Return ResourceManager.GetString("ReemplazoEnNombre_ToString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Conserva solo el texto entre los caracteres especificados, sin incluír los caracteres límite.
    '''</summary>
    Public Shared ReadOnly Property SoloEntreCaracteres_Descripcion() As String
        Get
            Return ResourceManager.GetString("SoloEntreCaracteres_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Solo entre caracteres (sin incluir la extension).
    '''</summary>
    Public Shared ReadOnly Property SoloEntreCaracteres_Nombre() As String
        Get
            Return ResourceManager.GetString("SoloEntreCaracteres_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Solo texto entre &quot;{1}&quot; y &quot;{2}&quot;.
    '''</summary>
    Public Shared ReadOnly Property SoloEntreCaracteres_ToString() As String
        Get
            Return ResourceManager.GetString("SoloEntreCaracteres_ToString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Convierte todo el nombre del archivo a mayúsculas.
    '''</summary>
    Public Shared ReadOnly Property TodoAMayusculas_Descripcion() As String
        Get
            Return ResourceManager.GetString("TodoAMayusculas_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Convertir todo a Mayúsculas.
    '''</summary>
    Public Shared ReadOnly Property TodoAMayusculas_Nombre() As String
        Get
            Return ResourceManager.GetString("TodoAMayusculas_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Convertir todo a Mayúsculas.
    '''</summary>
    Public Shared ReadOnly Property TodoAMayusculas_ToString() As String
        Get
            Return ResourceManager.GetString("TodoAMayusculas_ToString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Convierte todo el nombre del archivo a minúsculas.
    '''</summary>
    Public Shared ReadOnly Property TodoAMinusculas_Descripcion() As String
        Get
            Return ResourceManager.GetString("TodoAMinusculas_Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Convertir todo a Minúsculas.
    '''</summary>
    Public Shared ReadOnly Property TodoAMinusculas_Nombre() As String
        Get
            Return ResourceManager.GetString("TodoAMinusculas_Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Convertir todo a Minúsculas.
    '''</summary>
    Public Shared ReadOnly Property TodoAMinusculas_ToString() As String
        Get
            Return ResourceManager.GetString("TodoAMinusculas_ToString", resourceCulture)
        End Get
    End Property
End Class
